### ISSUE TITLE
[FEATURE] Make the events in in the Google Account

### ISSUE THREAD

**Issue by NOS73N** [rosenpin/Goaly#75]
**Is your feature request related to a problem? Please describe.**
I share my calendar with my company and family, and your events are not showing even after I share it with them

**Describe the solution you'd like**
I think it will be fix if you can make it like a event made it in my account directly, like "Orange theory" in my calendar, they do it automatically (don't know how)

**Additional context**
![SmartSelect_20240722_102352_Calendar](https://github.com/user-attachments/assets/cdc86d5b-aad1-4182-9fdb-01e001fdfe10)
![17216582534835388652851710507598](https://github.com/user-attachments/assets/9403be1e-6b0a-4b86-a42a-f638fd4db2c1)

**Comment by rosenpin** [comment]
Hi,  
Thank you for reaching out and sharing your experience.  

Goaly creates a separate calendar for its events, which is why they might not be showing up in your shared calendar. If you would like your company and family to see these events, you can share the Goaly calendar with them directly. This way, all Goaly events will be visible to everyone you share the calendar with.  

I hope this helps! If you have any other questions or need further assistance, please feel free to let us know.
